name = "QuantumOpticsAD"
uuid = "8ceb3a3c-6601-4354-b5f8-cfa045e9563d"
version = "0.1.0"
authors = ["chris "]

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
QuantumOpticsBase = "4f57444f-1401-5e15-980d-4471b28d5678"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.10"
ChainRulesCore = "1"
FFTW = "1"
ForwardDiff = "1"
LinearAlgebra = "1"
NLsolve = "4"
OrdinaryDiffEq = "6"
QuantumOpticsBase = "0.5"
Reexport = "1"
SciMLBase = "2"
SciMLSensitivity = "7"
Zygote = "0.7"
