name = "QuantumOpticsAD"
uuid = "8ceb3a3c-5353-4710-8588-379e49755294"
authors = ["Christy Varughese Mathew"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FFTW = "7a1cc6ca-4b0d-5927-9190-ebcc96c97138"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-5672a25197ac"
NLsolve = "27745e9c-f4dc-5a3d-90c3-568323a675e2"
OrdinaryDiffEq = "1dea7af3-3e0a-5c3c-9602-0da34447ef1e"
QuantumOptics = "6e0679c1-c302-5326-8c4c-a116f1df1846"
QuantumOpticsBase = "4f57444f-1785-5926-9c48-356391490251"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bcae4d3-0577-52c7-9669-b30f887c11fa"
SciMLSensitivity = "1ed8b502-7051-40fa-945b-7833075677a2"

[compat]
julia = "1.10"
QuantumOpticsBase = "0.5"
LinearAlgebra = "1.0"
SciMLBase = "1, 2"
SciMLSensitivity = "7"
OrdinaryDiffEq = "6"
NLsolve = "4"
FFTW = "1"
QuantumOptics = "1"
Reexport = "1"
ChainRulesCore = "1"